[package]
name = "spongedown"
version = "0.1.1"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "Converts markdown to html with svgbob support"
readme = "README.md"
repository = "https://github.com/ivanceras/spongedown"
documentation = "https://ivanceras.github.io/spongedown/"
keywords = ["markdown", "svg", "bob", "spongedown"]

[dependencies]
pulldown-cmark = "0.0"
svgbob = "0.1"
comic = "0.1"
csv = "0.15"
error-chain = "0.10"


[dev-dependencies]
handlebars = "0.21"
